INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (1, 'contig_n50', 'Contig N50', 'Median size of contigs in a genome assembly', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (2, 'total_genome_length', 'Total genome length', 'Total length of all genomic sequences', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (3, 'total_coding_sequence_length', 'Total coding sequence length', 'Total length of all coding sequences', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (4, 'total_gap_length', 'Total gap length', 'Total length of all gaps in a genome assembly', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (5, 'spanned_gaps', 'Spanned gaps', 'Number of gaps covered by sequencing reads', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (6, 'chromosomes', 'Chromosomes or plasmids', 'Number of structures in cells containing DNA', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (7, 'toplevel_sequences', 'Top level sequences', 'Primary sequences in a genome assembly', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (8, 'component_sequences', 'Component sequences', 'Part of the primary sequences in assembly', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (9, 'gc_percentage', 'Average GC content', 'Percentage of nucleotides in DNA that are G or C', 'percent');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (10, 'coding_genes', 'Coding genes', 'Genes that code for proteins', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (11, 'average_genomic_span', 'Average coding genomic span', 'Average length of all genomic regions', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (12, 'average_sequence_length', 'Average coding sequence length', 'Average length of sequences in genome', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (13, 'average_cds_length', 'Average CDS length', 'Average length of coding sequences', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (14, 'shortest_gene_length', 'Shortest coding gene', 'Length of shortest gene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (15, 'longest_gene_length', 'Longest coding gene', 'Length of longest gene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (16, 'total_transcripts', 'Transcripts in coding genes', 'Total number of RNA transcripts', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (17, 'coding_transcripts', 'Coding transcripts', 'Transcripts that code for proteins', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (18, 'transcripts_per_gene', 'Average transcripts per coding gene', 'Average number of transcripts per gene', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (19, 'coding_transcripts_per_gene', 'Average coding transcripts per gene', 'Average coding transcripts per gene', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (20, 'total_exons', 'Exons in coding genes', 'Total number of exons', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (21, 'total_coding_exons', 'Exons in coding genes', 'Total number of coding exons', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (22, 'average_exon_length', 'Average exon length', 'Average length of exons', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (23, 'average_coding_exon_length', 'Average exon length per coding gene', 'Average length of coding exons', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (24, 'average_exons_per_transcript', 'Average exons per coding transcript', 'Average exons per transcript', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (25, 'average_coding_exons_per_coding_transcript', 'Average coding exons per transcript', 'Average coding exons per coding transcript', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (26, 'total_introns', 'Introns in coding genes', 'Total number of introns', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (27, 'average_intron_length', 'Average intron length', 'Average intron length per coding gene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (28, 'nc_non_coding_genes', 'Non-coding genes', 'Genes that don''t code for proteins', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (29, 'nc_small_non_coding_genes', 'Small non-coding genes', 'Small genes not coding for proteins', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (30, 'nc_long_non_coding_genes', 'Long non-coding genes', 'Long genes not coding for proteins', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (31, 'nc_misc_non_coding_genes', 'Misc. non-coding genes', 'Miscellaneous non-coding genes', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (32, 'nc_average_genomic_span', 'Average non-coding genomic span', 'Mean length of all genomic regions', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (33, 'nc_average_sequence_length', 'Average non-coding sequence length', 'Mean length of all sequences', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (34, 'nc_shortest_gene_length', 'Shortest non-coding gene', 'Length of shortest gene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (35, 'nc_longest_gene_length', 'Longest non-coding gene', 'Length of longest gene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (36, 'nc_total_transcripts', 'Non-coding transcripts', 'Total RNA transcript count', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (37, 'nc_transcripts_per_gene', 'Average transcripts per non-coding gene', 'Mean transcripts count per gene', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (38, 'nc_total_exons', 'Exons in non-coding genes', 'Total exon count', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (39, 'nc_average_exon_length', 'Average exon length per non-coding transcript', 'Mean exon length', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (40, 'nc_average_exons_per_transcript', 'Average exons per non-coding transcript', 'Mean exon count per transcript', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (41, 'nc_total_introns', 'Introns in non-coding genes', 'Total intron count', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (42, 'nc_average_intron_length', 'Average intron length per non-coding transcript', 'Mean intron length', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (43, 'ps_pseudogenes', 'Pseudogenes', 'Genes which don''t code functional protiens', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (44, 'ps_average_genomic_span', 'Average pseudogene genomic span', 'Mean length of pseudogene regions', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (45, 'ps_average_sequence_length', 'Average pseudogene sequence length', 'Mean length of pseudogene sequences', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (46, 'ps_shortest_gene_length', 'Shortest pseudogene', 'Length of shortest pseudogene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (47, 'ps_longest_gene_length', 'Longest pseudogene', 'Length of longest pseudogene', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (48, 'ps_total_transcripts', 'Transcripts in pseudogenes', 'Total pseudogene RNA transcript count', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (49, 'ps_transcripts_per_gene', 'Average transcripts per pseudogene', 'Mean pseudogene transcripts count per pseudogene', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (50, 'ps_total_exons', 'Exons in pseudogenes', 'Total exon count in pseudogenes', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (51, 'ps_average_exon_length', 'Average exon length per pseudogene', 'Mean pseudogene exon length', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (52, 'ps_average_exons_per_transcript', 'Average intron length per pseudogene', 'Mean exon count per pseudogene transcript', 'float');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (53, 'ps_total_introns', 'Introns in pseudogenes', 'Total intron count in pseudogenes', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (54, 'ps_average_intron_length', 'Average intron length per pseudogene', 'Mean pseudogene intron length', 'bp');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (55, 'genes_with_orthologs', 'Genes with orthologs', 'Genes with orthologs in other species', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (56, 'homology_coverage', 'Coverage', 'Percent of genome which is homologous to another species', 'percent');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (57, 'short_variants', 'Short variants', 'Small-scale genetic variations', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (58, 'structural_variants', 'Structural variants', 'Large-scale genetic variations', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (59, 'short_variants_with_phenotype_assertions', 'Short variants
With phenotype assertions', 'Short variants with phenotypic evidence', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (60, 'short_variants_with_publications', 'Short variants
With publications', 'Short variants published in literature', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (61, 'short_variants_frequency_studies', 'Short variants
Frequency studies', 'Short variants studied for frequency', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (62, 'structural_variants_with_phenotype_assertions', 'Structural variants
With phenotype assertions', 'Structural variants with phenotypic evidence', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (63, 'enhancers', 'Enhancers', 'DNA sequences that increase gene expression', 'integer');
INSERT INTO attribute (attribute_id, name, label, description, type) VALUES (64, 'promoters', 'Promoters', 'DNA sequences initiating transcription', 'integer');
