# See the NOTICE file distributed with this work for additional information
#   regarding copyright ownership.
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#       http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
"""Check that a genome search index contains exactly the live genomes."""

import argparse
import json
from pathlib import Path
from typing import Any

from ensembl.utils.database import DBConnection

from ensembl.production.metadata.api.search.utils import get_all_live_genomes


def get_search_genome_uuids(search_index: dict[str, Any]) -> set[str]:
    """Return the genome UUIDs stored in a search index document.

    The search index generated by :mod:`search` stores a UUID as a field named
    ``genome_uuid`` in each entry. Entries without that field are ignored.
    """
    entries = search_index.get("entries")
    if not isinstance(entries, list):
        raise ValueError("Search index must contain an 'entries' list")

    genome_uuids = set()
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("Each search index entry must be an object")

        fields = entry.get("fields")
        if not isinstance(fields, list):
            raise ValueError("Each search index entry must contain a 'fields' list")

        for field in fields:
            if isinstance(field, dict) and field.get("name") == "genome_uuid":
                genome_uuid = field.get("value")
                if not isinstance(genome_uuid, str):
                    raise ValueError("Search index genome_uuid values must be strings")
                genome_uuids.add(genome_uuid)
                break

    return genome_uuids


def check_search_index(metadata_uri: str, search_json_path: str | Path) -> dict[str, list[str]]:
    """Compare live metadata genomes with genomes present in a search index.

    Returns a report containing genomes missing from the search index and
    genomes present in the search index that are not live in metadata.
    """
    with Path(search_json_path).open() as handle:
        search_index = json.load(handle)

    if not isinstance(search_index, dict):
        raise ValueError("Search index JSON must contain an object")

    search_genomes = get_search_genome_uuids(search_index)
    with DBConnection(metadata_uri).session_scope() as session:
        live_genomes = {genome.genome_uuid for genome in get_all_live_genomes(session)}

    return {
        "missing_from_search_index": sorted(live_genomes - search_genomes),
        "not_live_in_metadata": sorted(search_genomes - live_genomes),
    }


def main() -> None:
    """Run the search-index consistency check from the command line."""
    parser = argparse.ArgumentParser(description="Check a genome search index against live metadata genomes")
    parser.add_argument("--metadata-uri", required=True, help="Database URI for the metadata database")
    parser.add_argument("--search-json", required=True, help="Path to the generated search index JSON file")
    args = parser.parse_args()

    try:
        report = check_search_index(args.metadata_uri, args.search_json)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))

    print(json.dumps(report, indent=2))
    if report["missing_from_search_index"] or report["not_live_in_metadata"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
